# Data cleaning Notebook 

Suivant une nouvelle méthodologie, ce notebook orchestre simplement le travail. Toute la logique de nettoyage se trouve dans le fichier réutilisable `src/data_cleaning.py et data_loader.py` !

In [1]:
#Importation
import sys
from pathlib import Path

src_path = Path.cwd().parent / "src"
sys.path.append(str(src_path))

from utils import setup_logger, ensure_directory_exists
from data_loading import load_data
from data_cleaning import clean_missing_values, clean_total_charges, convert_churn_to_binary, add_derived_columns


#confi du looger
logger = setup_logger("../reports/logs/data_cleaning.log")

- Chargement des données

In [15]:
# Chemins des fichiers
INPUT_PATH = str(Path.cwd().parent / "data/raw/WA_Fn_Use_C_Telco_Customer_Churn.csv")
OUTPUT_PATH = str(Path.cwd().parent / "data/processed/churn_cleaned.csv")

#loading of data
df = load_data(INPUT_PATH)

#Appercu
print("Appercu des données: \n")
df.head()

2026-04-09 05:17:29,298 - INFO - |==> Chargement des données depuis e:\Certifs\Future_Interns\FUTURE_DS_02\data\raw\WA_Fn_Use_C_Telco_Customer_Churn.csv

Appercu des données:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

In [4]:
print(df.describe())

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [5]:
print("\n===Missing values===")
print(df.isnull().sum())

===Missing values===
customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [6]:
print("\nDuplicate rows:", df.duplicated().sum())

Duplicate rows: 0

- Nettoyage des données

In [16]:
# Nettoyage des données
df = clean_missing_values(df)
df = clean_total_charges(df)
df = convert_churn_to_binary(df)
df = add_derived_columns(df)

# Aperçu après nettoyage
print("Aperçu après nettoyage :")
display(df.head(10))

2026-04-09 05:17:39,920 - INFO - |==> Nettoyage des valeurs manquantes...
2026-04-09 05:17:39,945 - INFO - |==> Nettoyage de TotalCharges...
2026-04-09 05:17:39,973 - INFO - |==> Conversion du Churn en binaire...
2026-04-09 05:17:39,979 - INFO - |==> Ajout des colonnes dérivées...

Aperçu après nettoyage :

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,tenure_group
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0,0-6 mois
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,No,No,One year,No,Mailed check,56.95,1889.50,0,2-3 ans
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,0-6 mois
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,3-4 ans
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,0-6 mois
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,1,6-12 mois
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,0,1-2 ans
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,Month-to-month,No,Mailed check,29.75,301.90,0,6-12 mois
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,1,2-3 ans
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,0,5-6 ans

> Apres nettoyage et conversion en binaire; on vois aussi bien que la colunne `tenure_group` fut ajouté avec succes rendandant la taille `5 rows × 22 columns`

- Sauvegarde des données nettoyées

In [8]:
# Sauvegarde des données nettoyées
ensure_directory_exists(str(Path(OUTPUT_PATH).parent))
df.to_csv(OUTPUT_PATH, index=False)
logger.info(f"Data saved in {OUTPUT_PATH}")

2026-04-09 04:15:21,092 - INFO - Data saved in e:\Certifs\Future_Interns\FUTURE_DS_02\data\processed\churn_cleaned.csv